#pragma once
#include <iostream>
#include <cstdint>

enum class BattlecityBlocks : uint16_t
{
	Unknown = 0,

	CONSTRUCTION = L'╬',

	CONSTRUCTION_DESTROYED_DOWN = L'╩',
	CONSTRUCTION_DESTROYED_UP = L'╦',
	CONSTRUCTION_DESTROYED_LEFT = L'╠',
	CONSTRUCTION_DESTROYED_RIGHT = L'╣',
	CONSTRUCTION_DESTROYED_DOWN_TWICE = L'╨',
	CONSTRUCTION_DESTROYED_UP_TWICE = L'╥',
	CONSTRUCTION_DESTROYED_LEFT_TWICE = L'╞',
	CONSTRUCTION_DESTROYED_RIGHT_TWICE = L'╡',
	CONSTRUCTION_DESTROYED_LEFT_RIGHT = L'│',
	CONSTRUCTION_DESTROYED_UP_DOWN = L'─',
	CONSTRUCTION_DESTROYED_UP_LEFT = L'┌',
	CONSTRUCTION_DESTROYED_UP_RIGHT = L'┐',
	CONSTRUCTION_DESTROYED_DOWN_LEFT = L'└',
	CONSTRUCTION_DESTROYED_DOWN_RIGHT = L'┘',

	BULLET = L'•',

	AI_TANK_UP = L'?',
	AI_TANK_RIGHT = L'»',
	AI_TANK_DOWN = L'¿',
	AI_TANK_LEFT = L'«',

	OTHER_TANK_UP = L'˄',
	OTHER_TANK_RIGHT = L'˃',
	OTHER_TANK_DOWN = L'˅',
	OTHER_TANK_LEFT = L'˂',

	TANK_UP = L'▲',
	TANK_RIGHT = L'►',
	TANK_DOWN = L'▼',
	TANK_LEFT = L'◄',

	WORM_HOLE = L'ʘ',

	BOG = L'@',
	SAND = L'□',
	MOAT_HORIZONTAL = L'=',
	MOAT_VERTICAL = L'‖',
	HEDGEHOG = L'ͱ',
	BATTLE_WALL = L'☼',
	BANG = L'Ѡ',

	Space = L' ',

	BONUS_AMMO = '◊',
	MEDKIT = '☺'

};
